# See the docs: http://docs.readthedocs.io/en/latest/yaml-config.html
build:
    image: 2.0

python:
    version: 3
    setup_py_install: false

# Don't build any extra formats
formats: []

requirements_file: docs/requirements.txt
